--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2022-05-07 15:20:16


--
-- TOC entry 209 (class 1259 OID 30617)
-- Name: controllo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.controllo (
    codice integer NOT NULL,
    data_ora timestamp without time zone NOT NULL,
    referto character(100) NOT NULL,
    tipo character(50) NOT NULL,
    codice_dispositivo integer
);


ALTER TABLE public.controllo OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 30620)
-- Name: controllo_codice_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.controllo ALTER COLUMN codice ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.controllo_codice_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 30621)
-- Name: dato; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dato (
    id integer NOT NULL,
    data_ora timestamp without time zone NOT NULL,
    tipo character(20) NOT NULL,
    descrizione character(100) NOT NULL,
    valore double precision NOT NULL,
    nome character(30) NOT NULL,
    modalita character(30) NOT NULL
);


ALTER TABLE public.dato OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 30624)
-- Name: dato_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dato ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dato_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 30625)
-- Name: dispositivo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dispositivo (
    codice_dispositivo integer NOT NULL,
    marca character(50) NOT NULL,
    modello character(50) NOT NULL,
    tipo character(50) NOT NULL,
    metodo character(50) NOT NULL
);


ALTER TABLE public.dispositivo OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 30628)
-- Name: dispositivo_codice_dispositivo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dispositivo ALTER COLUMN codice_dispositivo ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.dispositivo_codice_dispositivo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 30629)
-- Name: elabora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elabora (
    id_dato integer NOT NULL,
    id_rilevazione integer NOT NULL,
    data_ora timestamp without time zone NOT NULL
);


ALTER TABLE public.elabora OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 30632)
-- Name: elabora_stream; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.elabora_stream (
    id_dato integer NOT NULL,
    id_sessione_rilevazione integer NOT NULL,
    data_ora timestamp without time zone NOT NULL
);


ALTER TABLE public.elabora_stream OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 30635)
-- Name: include; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.include (
    codice_sensore integer NOT NULL,
    codice_dispositivo integer NOT NULL
);


ALTER TABLE public.include OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 30638)
-- Name: patologia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.patologia (
    codice integer NOT NULL,
    nome character(30) NOT NULL,
    descrizione character(300) NOT NULL
);


ALTER TABLE public.patologia OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 30641)
-- Name: patologia_codice_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.patologia ALTER COLUMN codice ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.patologia_codice_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 30642)
-- Name: relativo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relativo (
    codice_controllo integer NOT NULL,
    codice_patologia integer NOT NULL
);


ALTER TABLE public.relativo OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 30645)
-- Name: rilevazione; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rilevazione (
    id integer NOT NULL,
    tipo character(100) NOT NULL,
    data_ora timestamp without time zone NOT NULL,
    unita_misura character(50) NOT NULL,
    valore character(50) NOT NULL,
    codice_dispositivo integer NOT NULL
);


ALTER TABLE public.rilevazione OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 30648)
-- Name: rilevazione_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rilevazione ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.rilevazione_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 30649)
-- Name: tipo_sensore; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tipo_sensore (
    id integer NOT NULL,
    unita_misura character(7) NOT NULL,
    tipo character(15) NOT NULL
);


ALTER TABLE public.tipo_sensore OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 30652)
-- Name: sensore_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tipo_sensore ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sensore_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 30653)
-- Name: sessione_rilevazione; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sessione_rilevazione (
    id integer NOT NULL,
    tipo character(100) NOT NULL,
    data_ora timestamp without time zone NOT NULL,
    unita_misura character(50) NOT NULL,
    nome_file character(50) NOT NULL,
    frequenza character(50) NOT NULL,
    codice_dispositivo integer NOT NULL
);


ALTER TABLE public.sessione_rilevazione OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 30656)
-- Name: sessione_rilevazione_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sessione_rilevazione ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.sessione_rilevazione_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3215 (class 2606 OID 30660)
-- Name: dispositivo codice_dispositivo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dispositivo
    ADD CONSTRAINT codice_dispositivo PRIMARY KEY (codice_dispositivo) INCLUDE (codice_dispositivo);


--
-- TOC entry 3223 (class 2606 OID 30662)
-- Name: sessione_rilevazione codice_sessione; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessione_rilevazione
    ADD CONSTRAINT codice_sessione PRIMARY KEY (id);


--
-- TOC entry 3211 (class 2606 OID 30658)
-- Name: controllo controllo_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.controllo
    ADD CONSTRAINT controllo_pk PRIMARY KEY (codice);


--
-- TOC entry 3213 (class 2606 OID 30664)
-- Name: dato dato_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dato
    ADD CONSTRAINT dato_pkey PRIMARY KEY (id);


--
-- TOC entry 3221 (class 2606 OID 30666)
-- Name: tipo_sensore id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tipo_sensore
    ADD CONSTRAINT id PRIMARY KEY (id) INCLUDE (id);


--
-- TOC entry 3219 (class 2606 OID 30668)
-- Name: rilevazione id_rilevazione; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rilevazione
    ADD CONSTRAINT id_rilevazione PRIMARY KEY (id);


--
-- TOC entry 3217 (class 2606 OID 30710)
-- Name: patologia patologia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.patologia
    ADD CONSTRAINT patologia_pkey PRIMARY KEY (codice);


--
-- TOC entry 3231 (class 2606 OID 30711)
-- Name: relativo codice_controllo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relativo
    ADD CONSTRAINT codice_controllo FOREIGN KEY (codice_controllo) REFERENCES public.controllo(codice) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3229 (class 2606 OID 30669)
-- Name: include codice_dispositivo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.include
    ADD CONSTRAINT codice_dispositivo FOREIGN KEY (codice_dispositivo) REFERENCES public.dispositivo(codice_dispositivo) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3234 (class 2606 OID 30674)
-- Name: sessione_rilevazione codice_dispositivo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sessione_rilevazione
    ADD CONSTRAINT codice_dispositivo FOREIGN KEY (codice_dispositivo) REFERENCES public.dispositivo(codice_dispositivo) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3233 (class 2606 OID 30679)
-- Name: rilevazione codice_dispositivo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rilevazione
    ADD CONSTRAINT codice_dispositivo FOREIGN KEY (codice_dispositivo) REFERENCES public.dispositivo(codice_dispositivo) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3230 (class 2606 OID 30684)
-- Name: include codice_sensore; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.include
    ADD CONSTRAINT codice_sensore FOREIGN KEY (codice_sensore) REFERENCES public.tipo_sensore(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3227 (class 2606 OID 30689)
-- Name: elabora_stream dato; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elabora_stream
    ADD CONSTRAINT dato FOREIGN KEY (id_dato) REFERENCES public.dato(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3225 (class 2606 OID 30694)
-- Name: elabora dato; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elabora
    ADD CONSTRAINT dato FOREIGN KEY (id_dato) REFERENCES public.dato(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3226 (class 2606 OID 30699)
-- Name: elabora rilevazione; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elabora
    ADD CONSTRAINT rilevazione FOREIGN KEY (id_rilevazione) REFERENCES public.rilevazione(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 3228 (class 2606 OID 30704)
-- Name: elabora_stream sessione; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.elabora_stream
    ADD CONSTRAINT sessione FOREIGN KEY (id_sessione_rilevazione) REFERENCES public.sessione_rilevazione(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2022-05-07 15:20:17

--
-- PostgreSQL database dump complete
--
TRUNCATE controllo RESTART IDENTITY CASCADE;
TRUNCATE patologia RESTART IDENTITY CASCADE;
TRUNCATE relativo RESTART IDENTITY CASCADE;
TRUNCATE dispositivo RESTART IDENTITY CASCADE;
TRUNCATE include RESTART IDENTITY CASCADE;
TRUNCATE tipo_sensore RESTART IDENTITY CASCADE;
TRUNCATE sessione_rilevazione RESTART IDENTITY CASCADE;
TRUNCATE rilevazione RESTART IDENTITY CASCADE;
TRUNCATE elabora_stream RESTART IDENTITY CASCADE;
TRUNCATE elabora RESTART IDENTITY CASCADE;
TRUNCATE dato RESTART IDENTITY CASCADE;



INSERT INTO dispositivo(marca,modello,tipo,metodo) VALUES('MGHBQCWVUJ1','EATJMDHPLD1','XBUWIJTERT1','OALBCUOGPO1');INSERT INTO dispositivo(marca,modello,tipo,metodo) VALUES('JHAFAIQSYB2','AEFVCWHFLV2','QUPWLFNYML2','ZNMMNCCWJV2');
INSERT INTO tipo_sensore(unita_misura,tipo) VALUES('m/s^2','accellerometro');INSERT INTO tipo_sensore(unita_misura,tipo) VALUES('gradi/s','giroscopio');INSERT INTO include(codice_sensore,codice_dispositivo) VALUES('2','1');


INSERT INTO patologia (nome, descrizione) VALUES ('Depressione','Stato danimo, temporaneo o persistente, caratterizzato da profonda tristezza, pessimismo, perdita di interessi e svalutazione delle proprie capacità.');
INSERT INTO patologia (nome, descrizione) VALUES ('Candida','La candidosi è un infezione micotica, quindi provocata da funghi, che nello specifico appartengono al genere Candida.');
INSERT INTO patologia (nome, descrizione) VALUES ('Diabete in gravidanza','Il diabete è una malattia ad evoluzione progressiva nel tempo (cronica) che provoca nell individuo un aumento dei livelli di zucchero (glucosio) nel sangue rispetto ai valori normali.');
INSERT INTO patologia (nome, descrizione) VALUES ('Ipertensione in gravidanza','Con ipertensione gravidica o gestazionale si intende un aumento transitorio dei valori di pressione arteriosa sopra i 140/90 mmHg (millimetri di mercurio).');
INSERT INTO patologia (nome, descrizione) VALUES ('Afasia','Turbe di gravità variabile del linguaggio parlato e scritto (sia in produzione che in comprensione)');
INSERT INTO patologia (nome, descrizione) VALUES ('Adenomiosi','Adenomiosi uterina è la presenza di ghiandole endometriali e stroma della muscolatura uterina; tende a causare un utero diffusamente aumentato di volume.');
INSERT INTO patologia (nome, descrizione) VALUES ('Amenorrea','Amenorrea è una mancanza di mestruazioni, e bisogna tener presente che esistono periodi della vita della donna nei quali tale mancanza è fisiologica: prima della pubertà, dopo la menopausa, durante la gravidanza e, per un periodo più o meno lungo, durante allattamento. ');
INSERT INTO patologia (nome, descrizione) VALUES ('Atrofia vaginale','Disturbo che si presenta di solito in menopausa, ma che può essere curato.');
INSERT INTO patologia (nome, descrizione) VALUES ('Cisti ovarica','Le cisti ovariche sono delle sacche ripiene di materiale liquido o solido, che si formano internamente o esternamente alle ovaie.');
INSERT INTO patologia (nome, descrizione) VALUES ('Infertilità femminile','Viene accertata quando una donna non riesce ad ottenere una gravidanza dopo 1-2 anni di rapporti intenzionalmente fertili, pur essendo teoricamente possibile per lei concepire ed avere un bambino. Si calcola che possa interessare il 15% circa delle donne.');
INSERT INTO patologia (nome, descrizione) VALUES ('Poliposi del colon','I polipi sono delle escrescenze di tessuto che si formano a partire dalla mucosa del colon.');
INSERT INTO patologia (nome, descrizione) VALUES ('Diverticolite','La diverticolite rappresenta il processo infiammatorio dei diverticoli, che sono delle estroflessioni localizzate lungo le pareti intestinali.');
INSERT INTO patologia (nome, descrizione) VALUES ('Irsutismo','L’irsutismo nella donna consiste nella crescita di peli in zone tipicamente maschili come l’addome, la schiena, il labbro superiore');
INSERT INTO patologia (nome, descrizione) VALUES ('Preeclampsia','Con preeclampsia si intende lo sviluppo di ipertensione o il peggioramento di ipertensione esistente accompagnata dalla presenza di un eccesso');
INSERT INTO patologia (nome, descrizione) VALUES ('Infezioni in gravidanza','La trasmissione di una infezione dalla madre al feto od al neonato, detta "trasmissione verticale", può avvenire durante la gravidanza, in coincidenza del parto o durante  l allattamento.');

INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\medico\1','Controllo del medico',2);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\medico\2','Controllo del medico',1);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\medico\3','Controllo del medico',3);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\dispositivo\test3','Controllo con dispositivo',1);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\dispositivo\test4','Controllo con dispositivo',1);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\dispositivo\test5','Controllo con dispositivo',1);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\dispositivom\test6','Controllo con dispositivo medico',2);
INSERT INTO controllo(data_ora,referto,tipo,codice_dispositivo) VALUES (LOCALTIMESTAMP(0),'\test1\dispositivom\test7','Controllo con dispositivo medico',2);

INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(1,1);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(2,2);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(3,3);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(3,4);


INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(4,4);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(5,4);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(6,4);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(7,4);
INSERT INTO relativo(codice_controllo,codice_patologia) VALUES
(8,4);
